# Site settings
title: LambdaSpace
email: methisnixt@gmail.com
description: >
    First web site
baseurl: "https://2aim1dis.github.io/githubpages-boilerplate"
url: "https://2aim1dis.github.io/githubpages-boilerplate"
twitter_username: LambdaWeb
github_username:  LambdaWeb

# Build settings
markdown: kramdown

include: ['_pages']
