# Site settings
title: LambdaSpace
email: methisnixt@gmail.com
description: >
    First web site
baseurl: "/githubpages-boilerplate"
url: "/githubpages-boilerplate"
twitter_username: LambdaWeb
github_username:  LambdaWeb

# Build settings
markdown: kramdown

include: ['_pages']
